spring.application.name=flight-reservation-system

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://db:5432/flight_booking_db
spring.datasource.username=postgres
spring.datasource.password=your_password

app.jwt.secret=yourVeryLongSecretKeyThatIsAtLeast256BitsLongForHS512Algorithm
app.jwt.access-token-expiration-ms=86400000
app.jwt.refresh-token-expiration-ms=604800000
server.port=9090

# Hibernate detects the dialect automatically
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable Open Session In View warning
spring.jpa.open-in-view=false
